ByTheWay/ByTheWay/Models/Adress.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ByTheWay.Models
{
    
    public class Adress
    {
        public string Number { get; set; }
        public float Distance { get; set; }

    }
}

ByTheWay/ByTheWay/Models/Intersection.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ByTheWay.Models
{
    public class Intersection
    {
        public string name { get; set; } //make it nullable!
        public List<Way> Connestions;
      
        public Intersection()
        {
            Connestions = new List<Way>();
        }
    }
}

ByTheWay/ByTheWay/Models/Road.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ByTheWay.Models
{
    public class Road : Way
    {
        public int MaxSpeed { get; set; }
        public float Length { get; set; }
        public string Name { get; set; }
        public List<Intersection> Connections;
        public List<Road> RoadLinks;

        public Road()
        {
            Connections = new List<Intersection>();
            RoadLinks = new List<Road>();
        }
    }
}

ByTheWay/ByTheWay/Models/Street.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ByTheWay.Models
{
    public class Street : Way
    {
        public int MaxSpeed { get; set; }
        public float Length { get; set; }
        public string Name { get; set; }
        public List<Adress> Adresses;
        public List<Intersection> Intersections;

        public Street()
        {
            Adresses = new List<Adress>();
            Intersections = new List<Intersection>();
        }
    }
}

ByTheWay/ByTheWay/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ByTheWay.Controllers
{
    public class HomeController : Controller
    {

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";
            
            return View();
        }
        public ActionResult Intersection()
        {
            return View();


        }
        public ActionResult Road()
        {
            return View();


        }
        public ActionResult Street()
        {
            return View();


        }

        public ActionResult Admin()
        {
            return View();
        }

        public ActionResult Adress()
        {
            return View();
        }

        public ActionResult Connections()
        {
            return View();
        }

        public ActionResult UserPage()
        {
            return View();
        }
    }

}

ByTheWay/ByTheWay/Controllers/UnicController.cs
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Text;
using Neo4jClient;
using Neo4jClient.Cypher;
using ByTheWay.Models;

namespace ByTheWay.Controllers
{
    public class UnicController : Controller
    {
        public GraphClient client;
        public static string firstname;
        public static string firstType;

        // GET: Street
        public ActionResult Street()
        {
            return View();
        }

        public void prepareConnection()
        {
            client = new GraphClient(new Uri("http://localhost:7474/db/data"), "neo4j", "sifra");

            try
            {
                client.Connect();
            }
            catch (Exception exc)
            {
                Console.WriteLine(exc);
            }
        }

        private void CreateUniqueRelationship(string Name1, string Name2 , bool twoWay, GraphClient client, string firstType, string secondType)
        {
            if (firstType == "Street")
            {
                if (secondType == "Adress")
                {
                    var query = client.Cypher
                    .Match("(p1:" + firstType + ")", "(p2:" + secondType + ")")
                    .Where((Street p1) => p1.Name == Name1)
                    .AndWhere((Adress p2) => p2.Number == Name2)
                    .CreateUnique("(p1)-[:Ima_adresu]->(p2)");
                    query.ExecuteWithoutResults();
                }
                else if (secondType == "Intersection")
                {
                    var query = client.Cypher
                    .Match("(p1:" + firstType + ")", "(p2:" + secondType + ")")
                    .Where((Street p1) => p1.Name == Name1)
                    .AndWhere((Intersection p2) => p2.name == Name2)
                    .CreateUnique("(p1)-[:Izlazi_na]->(p2)");
                    query.ExecuteWithoutResults();
                }
            }
            else if (firstType == "Road")
            {
                if (secondType == "Road")
                {
                    var query = client.Cypher
                    .Match("(p1:" + firstType + ")", "(p2:" + secondType + ")")
                    .Where((Road p1) => p1.Name == Name1)
                    .AndWhere((Road p2) => p2.Name == Name2)
                    .CreateUnique("(p1)-[:Povezan_sa]->(p2)");
                    query.ExecuteWithoutResults();
                }
                else if (secondType == "Intersection")
                {
                    var query = client.Cypher
                    .Match("(p1:" + firstType + ")", "(p2:" + secondType + ")")
                    .Where((Road p1) => p1.Name == Name1)
                    .AndWhere((Intersection p2) => p2.name == Name2)
                    .CreateUnique("(p1)-[:Izlazi_na]->(p2)");
                    query.ExecuteWithoutResults();
                }
            }
            else if (firstType == "Intersection")
            {
                if (secondType == "Road")
                {
                    var query = client.Cypher
                    .Match("(p1:" + firstType + ")", "(p2:" + secondType + ")")
                    .Where((Intersection p1) => p1.name == Name1)
                    .AndWhere((Road p2) => p2.Name == Name2)
                    .CreateUnique("(p1)-[:Vodi_na]->(p2)");
                    query.ExecuteWithoutResults();
                }
                else if (secondType == "Street")
                {
                    var query = client.Cypher
                    .Match("(p1:" + firstType + ")", "(p2:" + secondType + ")")
                    .Where((Intersection p1) => p1.name == Name1)
                    .AndWhere((Street p2) => p2.Name == Name2)
                    .CreateUnique("(p1)-[:Vodi_u]->(p2)");
                    query.ExecuteWithoutResults();
                }
            }
        }

        public void CreateEdge(UniModel model)
        {
            prepareConnection();

            string secondType = model.secondItem.ToString();
            string Name2 = model.ID2.ToString();
            bool twoWay = true;

            CreateUniqueRelationship(firstname, Name2, twoWay, client, firstType, secondType);
        }

        public void firstStreet(UniModel model)
        {
            prepareConnection();
            firstname = model.ID1.ToString();
            firstType = model.firstItem.ToString();
        }

        public void fillLists()
        {
            prepareConnection();
            Street st = new Street();
            Adress ad = new Adress();
            Road rd = new Road();
            Intersection ist = new Intersection();

            Dictionary<string, object> queryDict = new Dictionary<string, object>();
            var query = new Neo4jClient.Cypher.CypherQuery("start n=node(*) where (n:Street) return n", new Dictionary<string, object>(), CypherResultMode.Set);
            var query1 = new Neo4jClient.Cypher.CypherQuery("start n=node(*) where (n:Road) return n", new Dictionary<string, object>(), CypherResultMode.Set);
            var query2 = new Neo4jClient.Cypher.CypherQuery("start n=node(*) where (n:Adress) return n", new Dictionary<string, object>(), CypherResultMode.Set);
            var query3 = new Neo4jClient.Cypher.CypherQuery("start n=node(*) where (n:Intersection) return n", new Dictionary<string, object>(), CypherResultMode.Set);

            List<Street> streets = ((IRawGraphClient)client).ExecuteGetCypherResults<Street>(query).ToList();
            List<Road> roads = ((IRawGraphClient)client).ExecuteGetCypherResults<Road>(query1).ToList();
            List<Adress> adresses = ((IRawGraphClient)client).ExecuteGetCypherResults<Adress>(query2).ToList();
            List<Intersection> intersections = ((IRawGraphClient)client).ExecuteGetCypherResults<Intersection>(query3).ToList();

            UniModel.allStreets = new List<Models.Street>();
            UniModel.allRoads = new List<Models.Road>();
            UniModel.allAdresses = new List<Models.Adress>();
            UniModel.allIntersections = new List<Models.Intersection>();

            foreach (Street s in streets)
            {
                UniModel.allStreets.Add(s);
            }
            foreach (Road r in roads)
            {
                UniModel.allRoads.Add(r);
            }
            foreach (Adress a in adresses)
            {
                UniModel.allAdresses.Add(a);
            }
            foreach (Intersection i in intersections)
            {
                UniModel.allIntersections.Add(i);
            }
            writeToJSON();
        }

        public void writeToJSON()
        {
            prepareConnection();
            string rootPath = AppDomain.CurrentDomain.BaseDirectory;
            string path = @"" + rootPath + "Example.json";
            using (var tw = new StreamWriter(path, false))
            {
                tw.WriteLine("{");
                tw.WriteLine("\t" + "\"" + "nodes" + "\"" + ": [");
                foreach (Intersection its in UniModel.allIntersections)
                {
                    Dictionary<string, object> queryDict = new Dictionary<string, object>();
                    queryDict.Add("Name", its.name);
                    var query = new Neo4jClient.Cypher.CypherQuery("start n=node(*) where (n:Intersection) and exists(n.name) and n.name =~{Name} return id(n)",
                                                            queryDict, CypherResultMode.Set);
                    String maxId = ((IRawGraphClient)client).ExecuteGetCypherResults<String>(query).ToList().FirstOrDefault();

                    Intersection last = UniModel.allIntersections.Last();
                    tw.WriteLine("\t" + "\t" + "{");
                    tw.WriteLine("\t" + "\t" + "\t" + "\"" + "caption" + "\"" + ": " + "\"" + its.name + "\"" + ",");
                    tw.WriteLine("\t" + "\t" + "\t" + "\"" + "type" + "\"" + ": " + "" + "\"" + "\"" + ",");
                    tw.WriteLine("\t" + "\t" + "\t" + "\"" + "id" + "\"" + ": " + maxId);
                    if (its.Equals(last))
                    {
                        tw.WriteLine("\t" + "\t" + "}");
                    }
                    else
                    {
                        tw.WriteLine("\t" + "\t" + "},");
                    }
                }
                tw.WriteLine("\t" + "],");
                tw.WriteLine("\t" + "\"" + "edges" + "\"" + ": [");

                foreach (Street str in UniModel.allStreets)
                {
                    string tBox = str.Name;
                    Dictionary<string, object> queryDict = new Dictionary<string, object>();
                    queryDict.Add("Name", tBox);
                    var query = new Neo4jClient.Cypher.CypherQuery("start n = node(*) match(n) -[r:Izlazi_na]->(a) where exists(n.Name) and n.Name=~{Name} return a",
                                                                      queryDict, CypherResultMode.Set);
                    List<Intersection> raskrsniceZaUlicu = ((IRawGraphClient)client).ExecuteGetCypherResults<Intersection>(query).ToList();
                    if (raskrsniceZaUlicu.Count == 2)
                    {
                        Dictionary<string, object> queryDict1 = new Dictionary<string, object>();
                        queryDict1.Add("Name", raskrsniceZaUlicu[0].name);
                        Dictionary<string, object> queryDict2 = new Dictionary<string, object>();
                        queryDict2.Add("Name", raskrsniceZaUlicu[1].name);

                        var query1 = new Neo4jClient.Cypher.CypherQuery("start n=node(*) where (n:Intersection) and exists(n.name) and n.name =~{Name} return id(n)",
                                                                queryDict1, CypherResultMode.Set);

ByTheWay/ByTheWay/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ByTheWay/ByTheWay/Views/Home/Admin.cshtml
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>

<head>
    <title>Admin</title>
    <meta charset="utf-8" />
    <style type="text/css">
        body {
            background-color: beige;
            font-family: "Times New Roman", Times, serif;
            margin: 50px;
        }


        form {
            padding: 1em;
            border-style: solid;
            width: 25%;
            margin-left: 36%;
            margin-right: 44%;
            clear: left;
            height: 10%;
            text-align: center;
        }

        table {
            display: table;
            border-collapse: separate;
            border-spacing: 2px;
            border-color: grey;
            margin-left: 44.5%;
            margin-right: 40%;
            width: 10%;
        }

        header, footer {
            padding: 1em;
            color: white;
            background-color: black;
            clear: left;
            text-align: center;
        }
    </style>
    <style>
        .button {
            background-color: #008CBA;
            border: none;
            color: white;
            padding: 10px 25px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 13px;
            margin: 4px 2px;
            cursor: pointer;
        }
    </style>
</head>

<body>
    <div class="test1">
        <div class="col-md-4">
            <header>
                <h1>BY THE WAY</h1>
            </header>

            <p>


                @using (Html.BeginForm("Street", "Home"))
        {
            @Html.Label("Street Config")
        <p>
            <button class="button" type="submit">Street</button>
        </p>
}
                @using (Html.BeginForm("Road", "Home"))
        {
            @Html.Label("Road Config")
            <p>
                <button class="button" type="submit">Road</button>
            </p>
}

                @using (Html.BeginForm("Intersection", "Home"))
        {
            @Html.Label("Intersection Config")
            <p>
                <button class="button" type="submit">Intersection</button>
            </p>
}

                @using (Html.BeginForm("Adress", "Home"))
        {

            @Html.Label("Adress Config")
            <p>
                <button class="button" type="submit">Adress</button>
            </p>
}

                @using (Html.BeginForm("Connections", "Home"))
        {

            @Html.Label("Connections Config")
            <p>
                <button class="button" type="submit">Connections</button>
            </p>
}

            <table border="5">
                <tr>
                    <th> Data from Neo4j </th>
                </tr>
                <tr>
                    <td> <a href="@Url.Content("/HTMLPAGE.html")">Graficki prikaz</a></td>                    
                </tr>
                <tr>
                    <td> <a href="@Url.Content("/Neo4j graph show/display-graph.html")">NEO4J grafik</a></td>
                </tr>
            </table>    

                </p>
            </div>
        </div>
        <footer>Team- NIGHT&DAY</footer>
    </body>

ByTheWay/ByTheWay/Views/Home/Adress.cshtml
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>

<head>
    <title>Adress</title>
    <meta charset="utf-8" />
    <style type="text/css">
        body {
            background-color: beige;
            font-family: Verdana, Arial;
            margin: 50px;
        }

        h1 {
            margin-left: 40%;
        }

        form {
            padding: 1em;
            border-style: solid;
            width: 15%;
            margin-left: 43%;
            clear: left;
            height: 20%;
        }

        table {
            display: table;
            border-collapse: separate;
            border-spacing: 2px;
            border-color: grey;
            margin-left: 43%;
            width: 17%;
        }
    </style>
    <style>
        .inputclass {
            width: 100px;
            height: 25px;
            color: darkblue;
            padding-right: 100px;
        }

        .button {
            background-color: #008CBA;
            border: none;
            color: white;
            padding: 10px 25px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 13px;
            margin: 4px 2px;
            cursor: pointer;
        }

        .test1 {
            position: absolute;
        }
    </style>
</head>



<body>
    <div class="test1">
        <div class="col-md-4">
            <h1>Basic Adress operations</h1>

            @model ByTheWay.Models.Adress

            <table border="5">
                <tr>
                    <th>Data from Neo4j</th>
                </tr>
                <tr>
                    <td> @Html.Action("GetAdress", "Adress", Model)</td>
                    @*<td> @Html.Raw("\n")</td>*@
                </tr>
            </table>

            @using (Html.BeginForm("Admin", "Home"))
    {
        @Html.Label("Back to Admin page")
        <p>
            <button class="button" type="Admin page">Admin page</button>
        </p>
}

            @using (Html.BeginForm("addAdress", "Adress", FormMethod.Post))
    {
        @Html.Label("Number", new { @class = "inputclass" })
        @Html.TextBoxFor(model => model.Number)
        @Html.ValidationMessageFor(model => model.Number)
        @Html.Label("Distance", new { @class = "inputclass" })
        @Html.TextBoxFor(model => model.Distance)
        @Html.ValidationMessageFor(model => model.Distance)
        <button class="button" type="submit">Add New Adress</button>
}


            @using (Html.BeginForm("deleteAdress", "Adress", FormMethod.Post))
    {
        @Html.Label("Number", new { @class = "inputclass" })
        @Html.TextBoxFor(model => model.Number)
        @Html.ValidationMessageFor(model => model.Number)

        @Html.Label("Distance", new { @class = "inputclass" })
        @Html.TextBoxFor(model => model.Distance)
        @Html.ValidationMessageFor(model => model.Distance)
        <button class="button" type="submit"> Delete Adress </button>
}

            @using (Html.BeginForm("oldAdress", "Adress", FormMethod.Post))
    {
        @Html.Label("First write old street name and then new street name", new { @class = "inputclass" })
        @Html.Raw("\n")
        @Html.Raw("\n")
        @Html.Label("Number", new { @class = "inputclass" })
        @Html.TextBoxFor(model => model.Number)
        @Html.ValidationMessageFor(model => model.Number)
        @Html.Label("Distance", new { @class = "inputclass" })
        @Html.TextBoxFor(model => model.Distance)
        @Html.ValidationMessageFor(model => model.Distance)
        <button class="button" type="submit">Enter old Adress</button>
}


            @using (Html.BeginForm("changeAdress", "Adress", FormMethod.Post))
    {
        @Html.Label("Number", new { @class = "inputclass" })
        @Html.TextBoxFor(model => model.Number)
        @Html.ValidationMessageFor(model => model.Number)
        @Html.Label("Distance", new { @class = "inputclass" })
        @Html.TextBoxFor(model => model.Distance)
        @Html.ValidationMessageFor(model => model.Distance)
        <button class="button" type="submit">Change Adress</button>
}

            @using (Html.BeginForm("getStreetByAdress", "Adress", FormMethod.Post))
    {
        @Html.Label("Search string: ", new { @class = "inputclass" })
        @Html.TextBoxFor(model => model.Number)
        <button  class="button"type="submit">Find adress information</button>
}
            <p></p>
        </div>
    </div>
</body>

ByTheWay/ByTheWay/Views/Home/Connections.cshtml
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>

<head>
    <title>Connections</title>
    <meta charset="utf-8" />
    <style type="text/css">
        body {
            background-color: beige;
            font-family: Verdana, Arial;
            margin: 50px;
        }

        h1 {
            text-align: center;
        }

        form {
            padding: 1em;
            border-style: solid;
            width: 15%;
            margin-left: 40%;
            clear: left;
            height: 20%;
            border-right-width: 3px;
            padding-left: 10px;
            padding-right: 10px;
            text-align: center;
        }

        table {
            display: table;
            border-collapse: separate;
            border-spacing: 2px;
            border-color: grey;
            margin-left: 60%;
            width: 25%;
        }
    </style>
    <style>
        .inputclass {
            width: 10%;
            height: 10%;
            color: darkblue;
            padding-right: 100px;
            text-align: center;
        }

        .button {
            background-color: #008CBA;
            border: none;
            color: white;
            padding: 10px 25px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 13px;
            margin: 4px 2px;
            cursor: pointer;
        }

        .test1 {
            position: absolute;
        }
    </style>
</head>

<body>
    <div class="test1">
        <div class="col-md-4">
            <h1>Create new relationship between objects</h1>
            <p>
                @using (Html.BeginForm("Admin", "Home"))
                {
                    @Html.Label("Back to Admin page", new { @class = "inputclass" })
                <p>
                    <button class="button" type="Admin page">Admin page</button>
                </p>
            }

                @model ByTheWay.Models.UniModel
                @Html.Action("fillLists", "Unic", null)

                @using (Html.BeginForm("firstStreet", "Unic", FormMethod.Post))
                {
                    @Html.Label("Type of first object: ", new { @class = "inputclass" })
                    @Html.TextBoxFor(model => model.firstItem)
                    //@Html.ValidationMessageFor(model => model.Name)

                    @Html.Label("ID of first object: ", new { @class = "inputclass" })
                    @Html.TextBoxFor(model => model.ID1)
                    //@Html.ValidationMessageFor(model => model.MaxSpeed)

                    <button class="button" type="submit">Select first object</button>
                }

                @using (Html.BeginForm("CreateEdge", "Unic", FormMethod.Post))
                {
                    @Html.Label("Type of second object: ", new { @class = "inputclass" })
                    @Html.TextBoxFor(model => model.secondItem)
                    //@Html.ValidationMessageFor(model => model.Name)

                    @Html.Label("ID of second object: ", new { @class = "inputclass" })
                    @Html.TextBoxFor(model => model.ID2)
                    //@Html.ValidationMessageFor(model => model.MaxSpeed)

                    <button class="button" type="submit">Create relationship</button>
                }

                @Html.Label("ID's for different objects are: Street/Road -> Name  Intersection -> name  Adress -> Number", new { @class = "inputclass" })

                </p>
            </div>
        </div>
    </body>

ByTheWay/ByTheWay/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ByTheWay/ByTheWay/Views/Home/Index.cshtml
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>

<head>
    <title>Add Numbers</title>
    <meta charset="utf-8" />
    <style type="text/css">
        body {
            background-color: beige;
            font-family: Verdana, Arial;
            margin: 50px;
        }

        form {
            padding: 10px;
            border-style: solid;
            width: 250px;
        }
    </style>
</head>


<body>
    <div class="test1">
        <div class="col-md-4">
            <h1>Test osnovnih operacija</h1>



            @model ByTheWay.Models.Adress
            @using (Html.BeginForm("addAdress", "Adress", FormMethod.Post))
            {
                @Html.Label("Number")
                @Html.TextBoxFor(model => model.Number)
                @Html.ValidationMessageFor(model => model.Number)

                @Html.Label("Distance")
                @Html.TextBoxFor(model => model.Distance)
                @Html.ValidationMessageFor(model => model.Distance)
                <button type="submit">Add New Adress</button>
            }

            
            @using (Html.BeginForm("deleteAdress", "Adress", FormMethod.Post))
            {
                @Html.Label("Ovde je kod za brisanje ali je komentarisan trenutno")

                @*@Html.Label("Number")
                @Html.TextBoxFor(model => model.Number)
                @Html.ValidationMessageFor(model => model.Number)

                @Html.Label("Distance")
                @Html.TextBoxFor(model => model.Distance)
                @Html.ValidationMessageFor(model => model.Distance)
                <button type = "submit" > Delete Adress </button>*@


            }
            

            @using (Html.BeginForm("oldAdress", "Adress", FormMethod.Post))
            {
                @Html.Label("Prvo prosledite staru adresu pa nakon toga novu")
                @Html.Label("Number")
                @Html.TextBoxFor(model => model.Number)
                @Html.ValidationMessageFor(model => model.Number)
                
                @Html.Label("Distance")
                @Html.TextBoxFor(model => model.Distance)
                @Html.ValidationMessageFor(model => model.Distance)
                <button type="submit">Enter old Adress</button>
            }

            @using (Html.BeginForm("changeAdress", "Adress", FormMethod.Post))
            {
                @Html.Label("Number")
                @Html.TextBoxFor(model => model.Number)
                @Html.ValidationMessageFor(model => model.Number)
                
                @Html.Label("Distance")
                @Html.TextBoxFor(model => model.Distance)
                @Html.ValidationMessageFor(model => model.Distance)
                <button type="submit">Change Adress</button>
            }



            <p></p>
        </div>
    </div>
</body>

ByTheWay/ByTheWay/Views/Home/UserPage.cshtml
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>

<head>
    <title>Admin</title>
    <meta charset="utf-8" />
    <style type="text/css">
        body {
            background-color: beige;
            font-family: Verdana, Arial;
            margin: 50px;
        }

        form {
            padding: 10px;
            border-style: solid;
            width: 250px;
        }
    </style>
</head>

<body>
    <div class="test1">
        <div class="col-md-4">
            <h1>USER PAGE</h1>

            @using (Html.BeginForm("Admin", "Home"))
    {
        @Html.Label("Back to Admin page")
        <p>
            <button type="submit">Admin page</button>
        </p>
    }

                @model ByTheWay.Models.UniModel
                @using (Html.BeginForm("firstStreet", "Unic", FormMethod.Post))
                {
                    @Html.Label("String za pretragu: ")
                    @Html.TextBoxFor(model => model.ID1)
                    //@Html.ValidationMessageFor(model => model.MaxSpeed)

                <button type="submit">Pripremi prvi objekat</button>
                }

        </div>
    </div>
</body>